server:
  port: 9100

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jw_project?serverTimezone=GMT%2b8
    username: 你的用户名
    password: 你的密码
  redis:
    host: 127.0.0.1
    port: 6379
    password:

password:
  # 前后端传递密码的解密密钥
  decryptKey: areyouokareyouok

# 日志打印配置最好由nacos去管理
feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
logging:
  level:
    com.jw_server: debug