server:
  port: 9400

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jw_project?serverTimezone=GMT%2b8
    username: 你的用户名
    password: 你的密码
  servlet:
    multipart:
      # 上传单个文件大小限制
      max-file-size: 100MB
      #  总上传的数据大小限制
      max-request-size: 1024MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 人脸检测相关配置
dlFaceDetect:
  #添加人脸后是否自动更新人脸库
  autoUpdateFaceDatabase: false

python:
  socket:
    host: localhost
    port: 12345

#文件上传
upload:
  mode: local
  # 改成你的本地上传文件夹
  local:
    path: D:/IDEA/project/jw_project_cloud/static/upload/

# 日志打印配置最好由nacos去管理
feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
logging:
  level:
    com.jw_server: debug
